version: '3.7'

services:
  backend:
    volumes:
      - static:/static
    build:
      context: ./lithium
    ports:
      - "8000:8000"
      
  frontend:
    build:
      context: ./Client
    volumes:
      - frontend:/app/dist

  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
      - frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  static:
  frontend: